# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AudioStream' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod "youtube-ios-player-helper", "~> 0.1.1"
  pod 'SwiftWebSocket', '~> 2.7'
  # Pods for AudioStream

  target 'AudioStreamTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AudioStreamUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
